version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: laravel-app
    restart: always
    depends_on:
      - db  # MySQL doit démarrer avant Laravel
    ports:
      - "8081:80"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    command: ["/bin/bash", "-c", "/usr/local/bin/docker-init.sh && apache2-foreground"]

volumes:
  mysql_data:
